version: '3'

tasks:
  run:
    cmds:
      - go run . -s
  tailwind:
    cmds:
      - npx tailwindcss -c ./http/handler/src/tailwind.config.js -i ./http/handler/src/input.css -o ./http/handler/src/output.css 
  test:
    cmds:
      - go test -count=1 ./...
  new-migration:
    cmds:
      - migrate create -dir db/migrations -ext sql -seq $NAME
