name: Build and Upload Binary on Release

# Trigger the workflow on a release event
on:
  release:
    types:
      - created  # Trigger only when a new release is created

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions for the repo

jobs:
  build-and-upload:
    name: Build and Upload Go Binary
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Specify the Go version

      # Step 3: Install necessary dependencies for CGO, if required
      - name: Install C compiler (for CGO)
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      # Step 4: Build the Go project (enable CGO if required)
      - name: Build Go binary
        env:
          CGO_ENABLED: 1  # Enable CGO if needed
        run: |
          go build -o acc2 .

      # Step 5: Upload the built binary as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token provided by Actions
        with:
          upload_url: ${{ github.event.release.upload_url }}  # Upload URL provided by the release event
          asset_path: ./acc2  # Path to the built binary
          asset_name: acc2  # Name to use for the uploaded asset
          asset_content_type: application/octet-stream  # MIME type for binary files
