name: Build and Upload Binary on Release

# Trigger the workflow on a release event
on:
  release:
    types:
      - created  # Trigger only when a new release is created

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions for the repo

jobs:
  build-and-upload:
    name: Build and Upload Go Binary
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Specify the Go version

      # Build the binary targeting Alpine Linux (amd64 architecture)
      - name: Build Go binary for Alpine AMD64
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o expenses-alpine-amd64 .

      # Upload the artifact (binary or zip)
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./expenses-alpine-amd64  # Use binary file directly if not zipping
          asset_name: expenses-alpine-amd64
          asset_content_type: application/octet-stream
